/**
 * All theme-specific colors, words, and icons live here — components read
 * from the theme object instead of hardcoding soccer/dino strings, so new
 * themes are a matter of adding an entry.
 */
export const THEMES = {
  soccer: {
    key: 'soccer',
    colors: {
      bg: 'linear-gradient(160deg, #1b7a3d 0%, #2e9e56 55%, #1b6a38 100%)',
      card: '#ffffff',
      cardText: '#173d24',
      accent: '#f5c518',
      accentText: '#3d3000',
      meterFill: 'linear-gradient(90deg, #f5c518, #ffe27a)',
      chip: '#e8f6ec',
      headerText: '#ffffff',
    },
    terms: {
      celebration: 'GOAL!',
      celebrationSub: 'What a shot!',
      streak: 'Win Streak',
      progress: 'Match Progress',
      checking: 'Spending',
      savings: 'Season Fund',
      allDone: 'FULL TIME — you won the day! 🏆',
      rewards: 'Trophy Shop',
      pendingBanner: 'Waiting for the ref to check it!',
      rejectedBanner: 'No goal this time — ask a grown-up',
      mysteryTitle: 'Mystery Challenge!',
      mysteryTap: 'Tap to open the golden trophy box!',
      bonus: 'BONUS',
      goalTitle: 'My Trophy Goal',
      goalReached: 'YOU DID IT! Go get it in the Trophy Shop! 🏆',
      badges: 'Trophy Case',
      familyGoal: 'Team Goal',
      levelTitles: ['Rookie', 'Junior Striker', 'Striker', 'Playmaker', 'Team Captain', 'All-Star', 'MVP', 'Champion', 'Legend'],
      vacationTitle: 'Off-Season Break! 🏖️',
      vacationBody: 'No matches today — enjoy your break! Your Win Streaks are frozen safe and will be waiting when you get back.',
    },
    icons: {
      mascot: '⚽',
      streak: '🏅',
      savings: '🏆',
      checking: '💰',
      mystery: '🏆',
    },
    celebration: 'soccer',
    sound: 'goal',
    progressStyle: 'bar',
  },
  dino: {
    key: 'dino',
    colors: {
      bg: 'linear-gradient(160deg, #1f7a5c 0%, #2c9a74 55%, #14655f 100%)',
      card: '#fffaf0',
      cardText: '#2d3a1f',
      accent: '#f59e0b',
      accentText: '#3d2800',
      meterFill: 'linear-gradient(90deg, #f59e0b, #fbc963)',
      chip: '#f0f9e8',
      headerText: '#ffffff',
    },
    terms: {
      celebration: 'ROAR!',
      celebrationSub: 'Dino-mite job!',
      streak: 'Fossil Streak',
      progress: 'Hatch the Egg',
      checking: 'Spending',
      savings: 'Dino Nest Egg',
      allDone: 'The egg HATCHED! 🐣',
      rewards: 'Dino Store',
      pendingBanner: 'Waiting for a grown-up dino to check it!',
      rejectedBanner: 'Not this time — ask a grown-up',
      mysteryTitle: 'Mystery Egg!',
      mysteryTap: 'Tap to crack it open!',
      bonus: 'BONUS',
      goalTitle: 'My Dino Dream',
      goalReached: 'YOU DID IT! Go get it in the Dino Store! 🦖',
      badges: 'Fossil Collection',
      familyGoal: 'Herd Goal',
      levelTitles: ['Dino Egg', 'Hatchling', 'Little Raptor', 'Speedy Raptor', 'Junior Paleontologist', 'Dino Ranger', 'Raptor Boss', 'T-Rex Boss', 'Dino Legend'],
      vacationTitle: 'Dino Vacation! 🏝️',
      vacationBody: 'The dinos are taking a nap — no tasks today! Your Fossil Streaks are frozen safe until you’re back.',
    },
    icons: {
      mascot: '🦖',
      streak: '🦴',
      savings: '🥚',
      checking: '💰',
      mystery: '🥚',
    },
    celebration: 'dino',
    sound: 'roar',
    progressStyle: 'egg',
  },
  space: {
    key: 'space',
    colors: {
      bg: 'linear-gradient(160deg, #1a1f4b 0%, #2d3585 55%, #141838 100%)',
      card: '#f4f6ff',
      cardText: '#1c2350',
      accent: '#ffd94a',
      accentText: '#3d3000',
      meterFill: 'linear-gradient(90deg, #ffd94a, #ffe98f)',
      chip: '#e6ebff',
      headerText: '#ffffff',
    },
    terms: {
      celebration: 'BLAST OFF!',
      celebrationSub: 'Out of this world!',
      streak: 'Orbit Streak',
      progress: 'Mission Progress',
      checking: 'Spending',
      savings: 'Star Fund',
      allDone: 'MISSION COMPLETE — welcome home, astronaut! 🚀',
      rewards: 'Star Shop',
      pendingBanner: 'Waiting for Mission Control to check it!',
      rejectedBanner: 'Not this launch — ask a grown-up',
      mysteryTitle: 'Mystery Capsule!',
      mysteryTap: 'Tap to open the space capsule!',
      bonus: 'BONUS',
      goalTitle: 'My Space Dream',
      goalReached: 'YOU DID IT! Go get it in the Star Shop! 🚀',
      badges: 'Mission Patches',
      familyGoal: 'Crew Goal',
      levelTitles: ['Cadet', 'Rookie Pilot', 'Pilot', 'Co-Captain', 'Captain', 'Commander', 'Space Ranger', 'Star Voyager', 'Galaxy Legend'],
      vacationTitle: 'Space Station Break! 🛸',
      vacationBody: 'Mission Control says rest up — no missions today! Your Orbit Streaks are frozen safe until you land back home.',
    },
    icons: {
      mascot: '🚀',
      streak: '☄️',
      savings: '🌟',
      checking: '💰',
      mystery: '🛸',
    },
    celebration: 'space',
    sound: 'blastoff',
    progressStyle: 'bar',
  },
  fantasy: {
    key: 'fantasy',
    colors: {
      bg: 'linear-gradient(160deg, #6d28a8 0%, #9b4fd1 55%, #55217f 100%)',
      card: '#fdf7ff',
      cardText: '#43195f',
      accent: '#f5b8d9',
      accentText: '#5c1a3e',
      meterFill: 'linear-gradient(90deg, #f5b8d9, #fbdaec)',
      chip: '#f5ebfb',
      headerText: '#ffffff',
    },
    terms: {
      celebration: 'TA-DA!',
      celebrationSub: 'Simply enchanting!',
      streak: 'Magic Streak',
      progress: 'Royal Quest',
      checking: 'Spending',
      savings: 'Royal Treasury',
      allDone: 'THE WHOLE KINGDOM CHEERS! 👑',
      rewards: 'Royal Boutique',
      pendingBanner: 'Waiting for the Royal Court to check it!',
      rejectedBanner: 'Not this time — ask a grown-up',
      mysteryTitle: 'Enchanted Chest!',
      mysteryTap: 'Tap to break the magic seal!',
      bonus: 'BONUS',
      goalTitle: 'My Royal Wish',
      goalReached: 'YOU DID IT! Go get it in the Royal Boutique! 👑',
      badges: 'Crown Jewels',
      familyGoal: 'Kingdom Goal',
      levelTitles: ['Little Royal', 'Castle Helper', 'Court Apprentice', 'Knight', 'Royal Knight', 'Court Wizard', 'Crown Guardian', 'Royal Highness', 'Legend of the Realm'],
      vacationTitle: 'Royal Holiday! 🏰',
      vacationBody: 'The castle is on holiday — no quests today! Your Magic Streaks are safe under a protection spell until you return.',
    },
    icons: {
      mascot: '🦄',
      streak: '✨',
      savings: '💎',
      checking: '💰',
      mystery: '🔮',
    },
    celebration: 'fantasy',
    sound: 'magic',
    progressStyle: 'bar',
  },
  racing: {
    key: 'racing',
    colors: {
      bg: 'linear-gradient(160deg, #8f1d1d 0%, #c23b2e 55%, #6e1414 100%)',
      card: '#fffdf7',
      cardText: '#4a1414',
      accent: '#ffcf3f',
      accentText: '#3d3000',
      meterFill: 'linear-gradient(90deg, #ffcf3f, #ffe485)',
      chip: '#fdeee6',
      headerText: '#ffffff',
    },
    terms: {
      celebration: 'VROOM!',
      celebrationSub: 'Checkered flag!',
      streak: 'Race Streak',
      progress: 'Race to the Finish',
      checking: 'Spending',
      savings: 'Trophy Garage',
      allDone: 'CHECKERED FLAG — you won the race! 🏁',
      rewards: 'Speed Shop',
      pendingBanner: 'Waiting for the pit crew to check it!',
      rejectedBanner: 'Back to the pits — ask a grown-up',
      mysteryTitle: 'Mystery Pit Stop!',
      mysteryTap: 'Tap to open the toolbox!',
      bonus: 'BONUS',
      goalTitle: 'My Dream Ride',
      goalReached: 'YOU DID IT! Go get it in the Speed Shop! 🏁',
      badges: "Winner's Garage",
      familyGoal: 'Pit Crew Goal',
      levelTitles: ['Go-Kart Rookie', 'Street Racer', 'Speedster', 'Track Star', 'Pro Driver', 'Race Champion', 'Grand Prix Hero', 'World Champion', 'Legend of the Track'],
      vacationTitle: 'Pit Stop Break! 🏖️',
      vacationBody: 'The race is on pause — no laps today! Your Race Streaks are parked safe in the garage until you’re back.',
    },
    icons: {
      mascot: '🏎️',
      streak: '🏁',
      savings: '🏆',
      checking: '💰',
      mystery: '🧰',
    },
    celebration: 'racing',
    sound: 'vroom',
    progressStyle: 'bar',
  },
};

// Task categories now live in the database (parent-editable) and arrive
// with each /today payload — no hardcoded list here anymore.
