#!/usr/bin/env node
/**
 * Build docs/index.html — the single-file GitHub Pages demo.
 *
 * The demo is the real client bundle with client/demo/mock-api.js in front of
 * it answering /api/* from localStorage. This script builds that bundle with
 * vite.demo.config.js and folds the emitted JS and CSS back into the HTML, so
 * the result is one self-contained file with no asset requests.
 *
 * It is regenerated by CI on every push to main. The previous demo was a
 * hand-maintained blob and drifted months behind the app; the whole point of
 * this script is that nobody has to remember.
 *
 *   node scripts/build-demo.mjs
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const clientDir = path.join(root, 'client');
const distDir = path.join(clientDir, 'dist-demo');
const outFile = path.join(root, 'docs', 'index.html');

/**
 * String.replace with a string replacement expands $$, $&, $' and friends —
 * which quietly mangles any JS or CSS being spliced in ("$${x}" in a template
 * literal became "${x}", so money lost its dollar sign). A replacer function
 * is exempt from that substitution, so every splice here goes through one.
 */
function splice(source, needle, replacement) {
  if (!source.includes(needle)) throw new Error(`Expected to find ${needle} in the built HTML.`);
  return source.replace(needle, () => replacement);
}

console.log('Building the demo bundle…');
execFileSync('npx', ['vite', 'build', '--config', 'vite.demo.config.js'], {
  cwd: clientDir,
  stdio: 'inherit',
});

let html = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');

// An inline favicon, so the finished page makes no network requests at all —
// without one the browser goes looking for /favicon.ico and logs a 404.
// Injected here rather than in demo/index.html because Vite resolves every
// href in the entry HTML as an asset and drops tags it can't resolve.
const FAVICON =
  "<link rel=\"icon\" href=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' " +
  "viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%E2%AD%90%3C/text%3E%3C/svg%3E\">";
html = splice(html, '</head>', `  ${FAVICON}\n  </head>`);


/** Replace every <link>/<script> to a built asset with its inlined content. */
function inline(pattern, wrap) {
  html = html.replace(pattern, (match, href) => {
    const file = path.join(distDir, href.replace(/^\.?\//, ''));
    if (!fs.existsSync(file)) {
      throw new Error(`Referenced asset is missing from the build: ${href}`);
    }
    return wrap(fs.readFileSync(file, 'utf8'));
  });
}

inline(
  /<link[^>]+rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g,
  (css) => `<style>\n${css}\n</style>`
);
// The script is pulled out of <head> and re-inserted at the end of <body>.
// Vite emits it as a module, which is deferred; inlining it in place would
// make it a classic script that runs before #root exists, and React would
// fail with "target container is not a DOM element".
const scripts = [];
html = html.replace(
  /<script[^>]*type="module"[^>]*src="([^"]+)"[^>]*><\/script>/g,
  (match, src) => {
    const file = path.join(distDir, src.replace(/^\.?\//, ''));
    if (!fs.existsSync(file)) throw new Error(`Referenced script is missing: ${src}`);
    scripts.push(fs.readFileSync(file, 'utf8'));
    return '';
  }
);
if (scripts.length === 0) throw new Error('No module script found in the built HTML.');
html = splice(html, '</body>', `  <script>\n${scripts.join('\n')}\n</script>\n  </body>`);

// Belt and braces on the $-expansion trap above: if any splice ever mangles
// the payload again, the bundle won't appear verbatim in the output.
for (const js of scripts) {
  if (!html.includes(js)) throw new Error('The inlined bundle was altered during splicing.');
}

const leftovers = [...html.matchAll(/(?:src|href)="([^"]*assets\/[^"]+)"/g)].map((m) => m[1]);
if (leftovers.length) {
  throw new Error(
    `The demo would still request these files at runtime: ${leftovers.join(', ')}\n` +
      'Raise assetsInlineLimit in client/vite.demo.config.js so Vite emits them as data URIs.'
  );
}

html =
  '<!-- GENERATED FILE — do not edit.\n' +
  '     Built from client/demo/ + client/src/ by scripts/build-demo.mjs,\n' +
  '     and regenerated by CI on every push to main. Edit the source, not this. -->\n' +
  html;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, html);
fs.rmSync(distDir, { recursive: true, force: true });

console.log(`Wrote ${path.relative(root, outFile)} (${(html.length / 1024).toFixed(0)} KB)`);
